Refactor connected players check

diff --git a/common b/common
--- a/common
+++ b/common
@@ -37,6 +37,7 @@ supervisor_http_server_conf=/etc/supervisor/conf.d/http_server.conf
 # Status httpd config files
 status_http_server_conf=/etc/supervisor/conf.d/status_http_server.conf
 status_http_server_updater_conf=/etc/supervisor/conf.d/status_http_server_updater.conf
+cmd_valheim_status=/usr/local/bin/valheim-status
 
 # log levels
 debug=50
@@ -100,7 +101,12 @@ ensure_permissions() {
 
 
 server_is_idle() {
-    if timeout 3 tcpdump udp port "$SERVER_PORT" -n -s 84 -c 1 > /dev/null 2>&1; then
+    local status
+    "$cmd_valheim_status" > /dev/null 2>&1
+    status=$?
+    # valheim-status exits with 125 on error
+    # or the number of connected players on successful server query
+    if [ "$status" -gt 0 ] && [ "$status" -lt 125 ]; then
         return 1
     else
         return 0
