Initial BepInExPack mod support (Implements #282) (#288)
* Initial BepInExPack mod support (Fixes #282)

* Add BEPINEX info to README

* Refactored vpenvconf to work for generic BepInEx config files and support special characters in variable names

* Renamed vpenvconf -> env2cfg

* Unify ValheimPlus and BepInExPack mod install and update code

diff --git a/common b/common
--- a/common
+++ b/common
@@ -1,7 +1,9 @@
+#!/bin/bash
 # trap SIGUSR1 as it is being used to check
 # for process aliveness when an existing
 # pidfile is found
 trap ':' USR1
+just_started=${just_started:-true}
 
 # We are creating the following directory structure
 # /opt/valheim/
@@ -13,18 +15,31 @@ trap ':' USR1
 #
 valheim_download_path=/opt/valheim/dl/server    # Valheim server download directory
 valheim_install_path=/opt/valheim/server        # Valheim server installation directory
-vp_download_path=/opt/valheim/dl/plus           # ValheimPlus download directory
-vp_install_path=/opt/valheim/plus               # ValheimPlus installation directory
-vp_zipfile=UnixServer.zip                       # Name of the ValheimPlus archive
 valheim_restartfile="/tmp/valheim.restart"      # Signaling file created by valheim-updater
                                                 # or valheim-plus-updater that describes
                                                 # if and how to restart the server
+
+# ValheimPlus Mod
+vp_updater=/usr/local/bin/valheim-plus-updater
+vp_download_path=/opt/valheim/dl/plus           # ValheimPlus download directory
+vp_install_path=/opt/valheim/plus               # ValheimPlus installation directory
+vp_zipfile=UnixServer.zip                       # Name of the ValheimPlus archive
 vp_mergefile="$vp_download_path/merge"          # Signaling file created by valheim-updater
                                                 # that tells valheim-plus-updater that Valheim
                                                 # server was updated and needs to be merged
                                                 # with ValheimPlus
 vp_config_path="/config/valheimplus"
-just_started=${just_started:-true}
+
+# BepInEx Mod
+bepinex_updater=/usr/local/bin/bepinex-updater
+bepinex_download_path=/opt/valheim/dl/bepinex    # BepInEx download directory
+bepinex_install_path=/opt/valheim/bepinex        # BepInEx installation directory
+bepinex_config_path="/config/bepinex"
+bepinex_mergefile="$bepinex_download_path/merge" # Signaling file created by valheim-updater
+                                                 # that tells bepinex-updater that Valheim
+                                                 # server was updated and needs to be merged
+                                                 # with BepInEx
+bepinex_zipfile=BepInEx.zip                      # Name of the BepInEx archive
 
 # Collection of PID files
 valheim_server_pidfile=/var/run/valheim-server.pid
@@ -204,8 +219,41 @@ error_handler() {
 write_valheim_plus_config() {
     if [ -d "$vp_config_path" ]; then
         if env | grep "^$VALHEIM_PLUS_CFG_ENV_PREFIX" > /dev/null; then
-            /usr/local/bin/vpenvconf --verbose --config "$vp_config_path/valheim_plus.cfg" --env-prefix "$VALHEIM_PLUS_CFG_ENV_PREFIX"
+            /usr/local/bin/env2cfg --verbose --config "$vp_config_path/valheim_plus.cfg" --env-prefix "$VALHEIM_PLUS_CFG_ENV_PREFIX"
         fi
+    fi
+}
+
+
+write_bepinex_config() {
+    local config_path
+    if [ "$VALHEIM_PLUS" = true ]; then
+        config_path=$vp_config_path
+        plugins_path="$vp_install_path/BepInEx/plugins/"
+    elif [ "$BEPINEX" = true ]; then
+        config_path=$bepinex_config_path
+        plugins_path="$bepinex_install_path/BepInEx/plugins/"
+    else
+        error "Neither ValheimPlus nor BepInExPack enabled - not writing BepInEx config"
+        return 1
+    fi
+    if [ -n "$PRE_BEPINEX_CONFIG_HOOK" ]; then
+        info "Running pre BepInEx config hook: $PRE_BEPINEX_CONFIG_HOOK"
+        eval "$PRE_BEPINEX_CONFIG_HOOK"
+    fi
+    if [ -d "$config_path" ]; then
+        if env | grep "^$BEPINEX_CFG_ENV_PREFIX" > /dev/null; then
+            /usr/local/bin/env2cfg --verbose --config "$config_path/BepInEx.cfg" --env-prefix "$BEPINEX_CFG_ENV_PREFIX"
+        fi
+        if [ -d "$config_path/plugins" ] && [ -d "$plugins_path" ]; then
+            mkdir -p "$plugins_path"
+            info "Copying BepInEx plugins from $config_path/plugins/ -> $plugins_path"
+            find "$config_path/plugins/" -type f -iname '*.dll' -print -exec cp -f "{}" "$plugins_path" \;
+        fi
+    fi
+    if [ -n "$POST_BEPINEX_CONFIG_HOOK" ]; then
+        info "Running post BepInEx config hook: $POST_BEPINEX_CONFIG_HOOK"
+        eval "$POST_BEPINEX_CONFIG_HOOK"
     fi
 }
 
@@ -258,4 +306,178 @@ write_serverlist() {
         # shellcheck disable=SC2001
         echo "$id_list" | sed -e "s/ \\+/\\n/g" >> "$list_file"
     fi
+}
+
+
+extract_archive() {
+    local archive_path="$1"
+    local archive_file="$2"
+    cd "$archive_path" || fatal "Could not cd $archive_path"
+    debug "Extracting downloaded ZIP archive"
+    rm -rf extracted
+    mkdir -p extracted
+    unzip -d extracted/ "$archive_file"
+}
+
+
+download_mod() {
+    local download_url="$1"
+    local updated_at="$2"
+    local download_path="$3"
+    debug "Downloading $download_url to $download_path"
+    curl -sfSL -o "$download_path" "$download_url" \
+        && echo "$updated_at" > "$download_path.updated_at"
+}
+
+
+check_merge() {
+    local mergefile=$1
+    local download_path=$2
+    local zipfile=$3
+    local install_path=$4
+    local config_path=$5
+    local extraction_path=$6
+    local mod_name=$7
+
+    # The control file $mergefile is either created
+    # in prepare_mod() if the mod is being installed for
+    # the first time or an update is available, or
+    # it is created by valheim-updater if a Valheim server update
+    # was downloaded and the mod needs to be applied to it.
+    if [ -f "$mergefile" ]; then
+        info "Valheim dedicated server or $mod_name got updated - extracting and merging installation files"
+        (set -e; extract_archive "$download_path" "$zipfile" && merge_mod "$install_path" "$config_path" "$download_path/$extraction_path")
+        # shellcheck disable=SC2181
+        if [ $? -eq 0 ]; then
+            debug "Successfully installed $mod_name"
+            cp -f "$zipfile.updated_at" "$zipfile.installed_at"
+            rm -f "$mergefile"
+        else
+            error "Failed to extract and install $mod_name - retrying later"
+        fi
+    fi
+}
+
+
+prepare_mod() {
+    local download_url="$1"
+    local updated_at="$2"
+    local mergefile="$3"
+    local zipfile="$4"
+    download_mod "$download_url" "$updated_at" "$zipfile" \
+    && touch "$mergefile"
+}
+
+
+merge_mod() {
+    local mod_install_path="$1"
+    local mod_config_path="$2"
+    local mod_download_path="$3"
+    local config_file
+    local pkg_config_dir
+    local dest_file
+    mod_config_path=${mod_config_path%/}
+    mod_download_path=${mod_download_path%/}
+    debug "Merging Valheim server and mod"
+    # remove any old install directories
+    rm -rf "$mod_install_path.tmp" "$mod_install_path.old"
+    # create a new install directory where we will stage the new version
+    mkdir -p "$mod_install_path.tmp"
+    # rsync all Valheim dedicated server files
+    rsync -a --itemize-changes --exclude server_exit.drp --exclude steamapps "$valheim_download_path/" "$mod_install_path.tmp"
+    # rsync all ValheimPlus mod files on top of the dedicated server files
+    rsync -a --itemize-changes "$mod_download_path/" "$mod_install_path.tmp"
+    # if /config/valheimplus/ does not exist copy the default config from the ZIP archive
+    mkdir -p "$mod_config_path/plugins"
+    pkg_config_dir="$mod_install_path.tmp/BepInEx/config"
+    if [ -d "$pkg_config_dir" ]; then
+        cd "$pkg_config_dir" || fatal "Could not cd $pkg_config_dir"
+        for config_file in *; do
+            dest_file="$mod_config_path/$config_file"
+            # always copy the configs that came with the latest ZIP archive to .cfg.default
+            cp -f "$config_file" "$dest_file.default"
+            if [ ! -f "$dest_file" ]; then
+                debug "Config $dest_file does not exist - copying from archive"
+                cp -f "$config_file" "$dest_file"
+                if [ "$config_file" = "valheim_plus.cfg" ]; then
+                    write_valheim_plus_config
+                elif [ "$config_file" = "BepInEx.cfg" ]; then
+                    write_bepinex_config
+                fi
+            fi
+        done
+        cd - || fatal "Could not cd -"
+    fi
+    # ensure config file permissions
+    ensure_permissions
+    # remove the config folder within the server directory and symlink it to /config
+    rm -rf "$pkg_config_dir"
+    ln -s "$mod_config_path" "$pkg_config_dir"
+    # move an existing copy of ValheimPlus to the .old extension
+    if [ -d "$mod_install_path" ]; then
+        mv -f "$mod_install_path" "$mod_install_path.old"
+    fi
+    # move the staging folder to the live folder and signal valheim-updater to restart the server
+    mv "$mod_install_path.tmp" "$mod_install_path"
+    write_restart_file updated
+}
+
+
+check_for_mod_update() {
+    local download_url="$1"
+    local remote_updated_at="$2"
+    local zipfile="$3"
+    local mergefile="$4"
+    local download_path="$5"
+    local config_path="$6"
+    local extraction_path="$7"
+    local install_path="$8"
+    local mod_name="$9"
+    local local_updated_at
+    local local_installed_at
+
+    mkdir -p "$download_path" "$install_path"
+    cd "$download_path" || fatal "Could not cd $download_path"
+    if [ -f "$zipfile" ] && [ -f "$zipfile.updated_at" ] && [ -f "$zipfile.installed_at" ]; then
+        local_updated_at=$(< "$zipfile.updated_at")
+        local_installed_at=$(< "$zipfile.installed_at")
+        if [ "$local_updated_at" = "$remote_updated_at" ] && [ "$local_updated_at" = "$local_installed_at" ]; then
+            debug "Local $mod_name archive is identical to remote archive and was successfully installed - no update required"
+        else
+            info "Local $mod_name archive with update date $local_updated_at differs from date $remote_updated_at or failed to successfully install - updating"
+            prepare_mod "$download_url" "$remote_updated_at" "$mergefile" "$download_path/$zipfile"
+        fi
+    else
+        info "Fresh $mod_name install"
+        prepare_mod "$download_url" "$remote_updated_at" "$mergefile" "$download_path/$zipfile"
+    fi
+
+    check_merge "$mergefile" "$download_path" "$zipfile" "$install_path" "$config_path" "$extraction_path" "$mod_name"
+}
+
+
+iec_size_format() {
+    local byte_size=$1
+    local use_bc=false
+    local float_regex="^([0-9]+\\.?[0-9]*)\$"
+
+    if [ -z "$byte_size" ] || ! [[ "$byte_size" =~ $float_regex ]]; then
+        error "Input $byte_size is no valid float"
+        return 1
+    fi
+    if command -v bc > /dev/null 2>&1; then
+        use_bc=true
+    fi
+    for unit in B KiB MiB GiB TiB PiB EiB ZiB; do
+        if [ "${byte_size%.*}" -lt 1024 ]; then
+            printf "%.2f %s\\n" "$byte_size" "$unit"
+            return
+        fi
+        if [ "$use_bc" = true ]; then
+            byte_size=$(echo "$byte_size/1024" | bc -l)
+        else
+            byte_size=$((byte_size/1024))
+        fi
+    done
+    printf "%.2f YiB\\n" $byte_size
 }
diff --git a/valheim-server b/valheim-server
--- a/valheim-server
+++ b/valheim-server
@@ -14,6 +14,7 @@ valheim_server_pid=-1
 timeout=29
 kill_signal=TERM
 password_args=(-password "$SERVER_PASS")
+mod_name=none
 
 if [ "$VALHEIM_PLUS" = true ]; then
     cd "$vp_install_path" || fatal "Could not cd $vp_install_path"
@@ -24,7 +25,23 @@ if [ "$VALHEIM_PLUS" = true ]; then
     export LD_LIBRARY_PATH="$vp_install_path/linux64/:$vp_install_path/doorstop_libs/"
     SERVER_LD_PRELOAD=libdoorstop_x64.so
     valheim_server="$vp_install_path/valheim_server.x86_64"
-    [ -z "$SERVER_PASS" ] && password_args=()
+    if [ -z "$SERVER_PASS" ]; then
+        password_args=()
+    fi
+    mod_name="ValheimPlus"
+elif [ "$BEPINEX" = true ]; then
+    cd "$bepinex_install_path" || fatal "Could not cd $bepinex_install_path"
+    rm -rf "$bepinex_install_path.old"
+    export DOORSTOP_ENABLE=TRUE
+    export DOORSTOP_INVOKE_DLL_PATH="./BepInEx/core/BepInEx.Preloader.dll"
+    export DOORSTOP_CORLIB_OVERRIDE_PATH="./unstripped_corlib"
+    export LD_LIBRARY_PATH="$bepinex_install_path/linux64/:$bepinex_install_path/doorstop_libs/"
+    SERVER_LD_PRELOAD=libdoorstop_x64.so
+    valheim_server="$bepinex_install_path/valheim_server.x86_64"
+    if [ -z "$SERVER_PASS" ]; then
+        password_args=()
+    fi
+    mod_name="BepInEx"
 else
     cd "$valheim_install_path" || fatal "Could not cd $valheim_install_path"
     export LD_LIBRARY_PATH="$valheim_install_path/linux64/"
@@ -86,7 +103,7 @@ wait_for_server_listening() {
 run_server() {
     pre_server_run_hook
     info "Running Valheim Server"
-    debug "Server config is name: $SERVER_NAME, port: $SERVER_PORT/udp, world: $WORLD_NAME, public: $SERVER_PUBLIC, V+ mod: $VALHEIM_PLUS"
+    debug "Server config is name: $SERVER_NAME, port: $SERVER_PORT/udp, world: $WORLD_NAME, public: $SERVER_PUBLIC, mod: $mod_name"
     update_server_status starting
 
     # shellcheck disable=SC2086
