Additional pre and post hooks

diff --git a/valheim-plus-updater b/valheim-plus-updater
--- a/valheim-plus-updater
+++ b/valheim-plus-updater
@@ -27,7 +27,9 @@ check_for_update() {
     local download_url
     local remote_updated_at
     local remote_size
-    api_response=$(curl -sL https://api.github.com/repos/valheimPlus/ValheimPlus/releases/latest | jq -r ".assets[] | select(.name == \"$vp_zipfile\")")
+    if ! api_response=$(curl -sL https://api.github.com/repos/valheimPlus/ValheimPlus/releases/latest | jq -r ".assets[] | select(.name == \"$vp_zipfile\")"); then
+        fatal "Error: could not retrieve ValheimPlus release info from Github API"
+    fi
     download_url=$(jq -r  '.browser_download_url' <<< "${api_response}" )
     remote_updated_at=$(jq -r  '.updated_at' <<< "${api_response}" )
     remote_size=$(jq -r  '.size' <<< "${api_response}")
