BACKUPS_MAX_COUNT: Disable by default
Also use cd instead of pushd and error out if the backup directory was deleted at this exact moment somehow

diff --git a/valheim-backup b/valheim-backup
--- a/valheim-backup
+++ b/valheim-backup
@@ -91,11 +91,13 @@ flush_old() {
         return
     fi
 
-    info "Removing all but the newest $BACKUPS_MAX_COUNT backups"
-    pushd "$BACKUPS_DIRECTORY" > /dev/null
-    # shellcheck disable=SC2010
-    ls -tp | grep -v '/$' | tail -n +$((BACKUPS_MAX_COUNT+1)) | xargs -I {} rm -v -- {}
-    popd > /dev/null
+    if [ "$BACKUPS_MAX_COUNT" -gt 0 ]; then
+        info "Removing all but the newest $BACKUPS_MAX_COUNT backups"
+        cd "$BACKUPS_DIRECTORY" || fatal "Could not cd $BACKUPS_DIRECTORY"
+            # shellcheck disable=SC2010
+            ls -tp | grep -v '/$' | tail -n +$((BACKUPS_MAX_COUNT+1)) | xargs -I {} rm -v -- {}
+        cd -
+    fi
 
     info "Removing backups older than $BACKUPS_MAX_AGE days"
     find "$BACKUPS_DIRECTORY" -type f -mmin "+$((BACKUPS_MAX_AGE*60*24))" -name 'worlds-*.zip' -print -exec rm -f "{}" \;
