Detect correctly if Valheim or ValheimPlus download fails

diff --git a/valheim-updater b/valheim-updater
--- a/valheim-updater
+++ b/valheim-updater
@@ -35,6 +35,7 @@ main() {
     fi
 }
 
+
 update() {
     local logfile
     if ! is_idle; then
@@ -43,7 +44,14 @@ update() {
     pre_update_check_hook
     logfile="$(mktemp)"
     info "Downloading/updating/validating Valheim server from Steam"
-    download_valheim
+    if ! download_valheim; then
+        if [ -f "$valheim_download_path/valheim_server.x86_64" ]; then
+            error "Failed to update Valheim server from Steam - however an old version was found - trying to start"
+        else
+            error "Failed to download Valheim server from Steam - retrying later - check your networking and volume access permissions"
+            return
+        fi
+    fi
     rsync -a --itemize-changes --delete --exclude server_exit.drp --exclude steamapps "$valheim_download_path/" "$valheim_install_path" | tee "$logfile"
     if grep '^[*>]' "$logfile" > /dev/null 2>&1; then
         info "Valheim Server was updated - restarting"
