Add shellcheck tests

diff --git a/valheim-plus-updater b/valheim-plus-updater
--- a/valheim-plus-updater
+++ b/valheim-plus-updater
@@ -22,16 +22,20 @@ create_directory_structure() {
 
 
 check_for_update() {
-    cd "$vp_download_path"
-    local api_response=$(curl -sL https://api.github.com/repos/valheimPlus/ValheimPlus/releases/latest | jq -r ".assets[] | select(.name == \"$vp_zipfile\")")
-    local download_url=$(jq -r  '.browser_download_url' <<< "${api_response}" )
-    local remote_updated_at=$(jq -r  '.updated_at' <<< "${api_response}" )
-    local remote_size=$(jq -r  '.size' <<< "${api_response}")
+    cd "$vp_download_path" || exit
+    local api_response
+    local download_url
+    local remote_updated_at
+    local remote_size
+    api_response=$(curl -sL https://api.github.com/repos/valheimPlus/ValheimPlus/releases/latest | jq -r ".assets[] | select(.name == \"$vp_zipfile\")")
+    download_url=$(jq -r  '.browser_download_url' <<< "${api_response}" )
+    remote_updated_at=$(jq -r  '.updated_at' <<< "${api_response}" )
+    remote_size=$(jq -r  '.size' <<< "${api_response}")
 
-    if [ -f "$vp_zipfile" -a -f "$vp_zipfile.updated_at" ]; then
+    if [ -f "$vp_zipfile" ] && [ -f "$vp_zipfile.updated_at" ]; then
         local_updated_at=$(< "$vp_zipfile.updated_at")
         local_size=$(stat --format="%s" "$vp_zipfile")
-        if [ "$local_updated_at" = "$remote_updated_at" -a "$local_size" = "$remote_size" ]; then
+        if [ "$local_updated_at" = "$remote_updated_at" ] && [ "$local_size" = "$remote_size" ]; then
             debug "Local ValheimPlus archive is identical to remote archive - no update required"
         else
             info "Local ValheimPlus archive with size $local_size and update date $local_updated_at differs from remote size $remote_size and date $remote_updated_at - updating"
@@ -58,7 +62,7 @@ check_for_update() {
 prepare_valheim_plus() {
     local download_url="$1"
     local updated_at="$2"
-    download_valheim_plus "$download_url" $updated_at \
+    download_valheim_plus "$download_url" "$updated_at" \
         && extract_valheim_plus \
         && touch "$vp_mergefile"
 }
@@ -70,7 +74,7 @@ merge_valheim_plus() {
     mkdir -p "$vp_install_path.tmp"
     rsync -a --itemize-changes --exclude server_exit.drp --exclude steamapps "$valheim_download_path/" "$vp_install_path.tmp"
     rsync -a --itemize-changes "$vp_download_path/extracted/" "$vp_install_path.tmp"
-    if [ ! -d "$vp_config_path" -a -d "$vp_install_path.tmp/BepInEx/config" ]; then
+    if [ ! -d "$vp_config_path" ] && [ -d "$vp_install_path.tmp/BepInEx/config" ]; then
         cp -a "$vp_install_path.tmp/BepInEx/config" "$vp_config_path"
         ensure_permissions
         write_valheim_plus_config
@@ -96,11 +100,11 @@ download_valheim_plus() {
 
 
 extract_valheim_plus() {
-    cd "$vp_download_path"
+    cd "$vp_download_path" || fatal "Could not cd $vp_download_path"
     debug "Extracting downloaded ValheimPlus ZIP archive"
     rm -rf extracted
     mkdir -p extracted
-    unzip -d extracted/ $vp_zipfile
+    unzip -d extracted/ "$vp_zipfile"
 }
 
 
diff --git a/valheim-server b/valheim-server
--- a/valheim-server
+++ b/valheim-server
@@ -16,7 +16,7 @@ kill_signal=TERM
 password_args=(-password "$SERVER_PASS")
 
 if [ "$VALHEIM_PLUS" = true ]; then
-    cd "$vp_install_path"
+    cd "$vp_install_path" || fatal "Could not cd $vp_install_path"
     rm -rf "$vp_install_path.old"
     export DOORSTOP_ENABLE=TRUE
     export DOORSTOP_INVOKE_DLL_PATH="./BepInEx/core/BepInEx.Preloader.dll"
@@ -26,7 +26,7 @@ if [ "$VALHEIM_PLUS" = true ]; then
     valheim_server="$vp_install_path/valheim_server.x86_64"
     [ -z "$SERVER_PASS" ] && password_args=()
 else
-    cd "$valheim_install_path"
+    cd "$valheim_install_path" || fatal "Could not cd $valheim_install_path"
     export LD_LIBRARY_PATH="$valheim_install_path/linux64/"
     valheim_server="$valheim_install_path/valheim_server.x86_64"
 fi
@@ -96,7 +96,7 @@ filter() {
             log_filter=$SERVER_LOG_STDERR_FILTER
             ;;
     esac
-    eval $log_filter
+    eval "$log_filter"
 }
 
 
@@ -109,10 +109,10 @@ shutdown() {
     fi
     info "Shutting down Valheim Server with PID $valheim_server_pid"
     kill -INT $valheim_server_pid
-    shutdown_timeout=$(($(date +%s)+$timeout))
+    shutdown_timeout=$(($(date +%s)+timeout))
     while [ -d "/proc/$valheim_server_pid" ]; do
-        if [ $(date +%s) -gt $shutdown_timeout ]; then
-            shutdown_timeout=$(($(date +%s)+$timeout))
+        if [ "$(date +%s)" -gt $shutdown_timeout ]; then
+            shutdown_timeout=$(($(date +%s)+timeout))
             warn "Timeout while waiting for server to shutdown - sending SIG$kill_signal to PID $valheim_server_pid"
             kill -$kill_signal $valheim_server_pid
             case "$kill_signal" in
diff --git a/valheim-updater b/valheim-updater
--- a/valheim-updater
+++ b/valheim-updater
@@ -9,7 +9,7 @@
 . /usr/local/etc/valheim/common
 
 debug "Running Valheim Server updater as user $USER uid $UID"
-cd /opt/steamcmd
+cd /opt/steamcmd || fatal "Could not cd /opt/steamcmd"
 pidfile=$valheim_updater_pidfile
 just_started=true
 next_update=$(date +%s)
@@ -25,8 +25,8 @@ main() {
             ensure_permissions
             update
             check_server_restart
-            next_update=$(($(date +%s)+$UPDATE_INTERVAL))
-            while [ $run = true -a $(date +%s) -lt $next_update ]; do
+            next_update=$(($(date +%s)+UPDATE_INTERVAL))
+            while [ $run = true ] && [ "$(date +%s)" -lt $next_update ]; do
                 sleep 5
             done
         done
@@ -38,12 +38,12 @@ main() {
 
 
 update() {
-    local logfile="$(mktemp)"
+    local logfile
+    logfile="$(mktemp)"
     info "Downloading/updating/validating Valheim server from Steam"
     download_valheim
     rsync -a --itemize-changes --delete --exclude server_exit.drp --exclude steamapps "$valheim_download_path/" "$valheim_install_path" | tee "$logfile"
-    grep '^[*>]' "$logfile" > /dev/null 2>&1
-    if [ $? -eq 0 ]; then
+    if grep '^[*>]' "$logfile" > /dev/null 2>&1; then
         info "Valheim Server was updated - restarting"
         check_valheim_plus updated
         echo restart > "$valheim_restartfile"
@@ -68,7 +68,7 @@ check_valheim_plus() {
         fi
         /usr/local/bin/valheim-plus-updater
     else
-        if [ "$1" = updated -a -d "$vp_install_path" ]; then
+        if [ "$1" = updated ] && [ -d "$vp_install_path" ]; then
             debug "ValheimPlus currently disabled but previously installed - keeping installation fresh"
             debug "If this is unwanted remove $vp_install_path"
             touch "$vp_mergefile"
@@ -79,17 +79,18 @@ check_valheim_plus() {
 
 
 download_valheim() {
-    /opt/steamcmd/steamcmd.sh +login anonymous +force_install_dir "$valheim_download_path" +app_update 896660 $STEAMCMD_ARGS +quit
+    /opt/steamcmd/steamcmd.sh +login anonymous +force_install_dir "$valheim_download_path" +app_update 896660 "$STEAMCMD_ARGS" +quit
 }
 
 
 check_server_restart() {
+    local mode
     # The control file $valheim_restartfile is either created
     # by update() if Valheim is being installed for the first
     # time or has been updated, or by valheim-plus-updater if
     # a new version of the mod has been downloaded.
     if [ -f "$valheim_restartfile" ]; then
-        local mode=$(< "$valheim_restartfile")
+        mode=$(< "$valheim_restartfile")
         rm -f "$valheim_restartfile"
 
         case "$mode" in
@@ -112,7 +113,7 @@ update_now() {
 
 
 shutdown() {
-    clear_lock $pidfile
+    clear_lock "$pidfile"
     run=false
 }
 
